### ISSUE TITLE
The question about the calculation of mAP

### ISSUE THREAD

**Issue by qujz** [Forrest-ht/AdaptiveMargin#1]
Hello, thank you for sharing the code. When I read the code, I found that you used the following method when calculating mAP：
for ii in range(len(precision)):
                    precision[ii] = max(precision[ii:])
Why use this method instead of calculating the mean of original precision list? Thank you.

**Comment by Forrest-ht** [comment]
Thank you for your attention.

**Comment by Forrest-ht** [comment]
Thank you for your attention.  You are right,  the mean of original precision  should be adopted as AP of each sample for the standard mAP in image retrieval.  But this imporved verison of mAP is borrowed from the[ paper](https://github.com/iMoonLab/PVRNet) and the  [code](https://github.com/iMoonLab/PVRNet/blob/master/utils/meter/retrievalmeter.py).
For the consisitency of experiment results from the cited papers, we use this version of mAP.
We will release the new model  evaluated on the standard mAP.

**Comment by Forrest-ht** [comment]
I close this. if there are other questions, please tell us.
